# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hema-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - lihaohong/yazi
        - dejan/lazygit
        - shengis/mako 
        - alternateved/cliphist
        - skoved/rmpc
    install:
      packages:
        - rmpc
        - openscad
        - cliphist
        - stow
        - zathura
        - zathura-pdf-poppler
        - grimpicker
        - kde-connect
        - fastfetch
        - nvim
        - yazi
        - zoxide
        - tmux
        - zsh
        - kitty
        - lazygit
        - mako
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    remove:
      packages:
        - foot
        - just
        - dunst

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.musicbrainz.Picard
          - io.mpv.Mpv
          - org.kde.krita
          - org.inkscape.Inkscape
          - org.libreoffice.LibreOffice
          - org.mozilla.Thunderbird
          - com.dropbox.Client
          - md.obsidian.Obsidian
          - com.ultimaker.cura
          - app.grayjay.Grayjay
          - com.spotify.Client
          - com.sweethome3d.Sweethome3d
      - scope: user # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password
  
  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka 
        - Hack
        - Noto
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
